sonar.projectKey=CinemaMicroservices
sonar.working.directory=C:\\Users\\phatd\\source\\repos\\CinemaBookingSystem\\.sonarqube\\out\\.sonar
sonar.projectBaseDir=C:\\Users\\phatd\\source\\repos\\CinemaBookingSystem
sonar.pullrequest.cache.basepath=C:\\Users\\phatd\\source\\repos\\CinemaBookingSystem
sonar.sources=\
"C:\\Users\\phatd\\source\\repos\\CinemaBookingSystem\\.vs\\CinemaBookingSystem.slnx\\v18\\DocumentLayout.backup.json",\
"C:\\Users\\phatd\\source\\repos\\CinemaBookingSystem\\.vs\\CinemaBookingSystem.slnx\\v18\\DocumentLayout.json",\
"C:\\Users\\phatd\\source\\repos\\CinemaBookingSystem\\docker-compose.yml"

002A7D58-A1B1-CBE3-8F7A-0F0027BEE5A6.sonar.projectKey=CinemaMicroservices:002A7D58-A1B1-CBE3-8F7A-0F0027BEE5A6
002A7D58-A1B1-CBE3-8F7A-0F0027BEE5A6.sonar.projectName=Cinema.Notification.Worker
002A7D58-A1B1-CBE3-8F7A-0F0027BEE5A6.sonar.projectBaseDir=C:\\Users\\phatd\\source\\repos\\CinemaBookingSystem\\Cinema.Notification.Worker
002A7D58-A1B1-CBE3-8F7A-0F0027BEE5A6.sonar.sourceEncoding=utf-8
002A7D58-A1B1-CBE3-8F7A-0F0027BEE5A6.sonar.tests=
002A7D58-A1B1-CBE3-8F7A-0F0027BEE5A6.sonar.sources=\
"C:\\Users\\phatd\\source\\repos\\CinemaBookingSystem\\Cinema.Notification.Worker\\Program.cs",\
"C:\\Users\\phatd\\source\\repos\\CinemaBookingSystem\\Cinema.Notification.Worker\\Worker.cs",\
"C:\\Users\\phatd\\source\\repos\\CinemaBookingSystem\\Cinema.Notification.Worker\\obj\\Debug\\net8.0\\Cinema.Notification.Worker.GlobalUsings.g.cs",\
"C:\\Users\\phatd\\source\\repos\\CinemaBookingSystem\\Cinema.Notification.Worker\\obj\\Debug\\net8.0\\.NETCoreApp,Version=v8.0.AssemblyAttributes.cs",\
"C:\\Users\\phatd\\source\\repos\\CinemaBookingSystem\\Cinema.Notification.Worker\\obj\\Debug\\net8.0\\Cinema.Notification.Worker.AssemblyInfo.cs",\
"C:\\Users\\phatd\\source\\repos\\CinemaBookingSystem\\Cinema.Notification.Worker\\appsettings.Development.json",\
"C:\\Users\\phatd\\source\\repos\\CinemaBookingSystem\\Cinema.Notification.Worker\\appsettings.json",\
"C:\\Users\\phatd\\source\\repos\\CinemaBookingSystem\\Cinema.Notification.Worker\\Dockerfile",\
"C:\\Users\\phatd\\source\\repos\\CinemaBookingSystem\\Cinema.Notification.Worker\\Properties\\launchSettings.json",\
"C:\\Users\\phatd\\source\\repos\\CinemaBookingSystem\\Cinema.Notification.Worker\\obj\\Cinema.Notification.Worker.csproj.nuget.dgspec.json",\
"C:\\Users\\phatd\\source\\repos\\CinemaBookingSystem\\Cinema.Notification.Worker\\obj\\project.assets.json",\
"C:\\Users\\phatd\\source\\repos\\CinemaBookingSystem\\Cinema.Notification.Worker\\bin\\Debug\\net8.0\\appsettings.Development.json",\
"C:\\Users\\phatd\\source\\repos\\CinemaBookingSystem\\Cinema.Notification.Worker\\bin\\Debug\\net8.0\\appsettings.json",\
"C:\\Users\\phatd\\source\\repos\\CinemaBookingSystem\\Cinema.Notification.Worker\\bin\\Debug\\net8.0\\Cinema.Notification.Worker.deps.json",\
"C:\\Users\\phatd\\source\\repos\\CinemaBookingSystem\\Cinema.Notification.Worker\\bin\\Debug\\net8.0\\Cinema.Notification.Worker.runtimeconfig.json"

002A7D58-A1B1-CBE3-8F7A-0F0027BEE5A6.sonar.cs.analyzer.projectOutPaths=\
"C:\\Users\\phatd\\source\\repos\\CinemaBookingSystem\\.sonarqube\\out\\0"
002A7D58-A1B1-CBE3-8F7A-0F0027BEE5A6.sonar.cs.roslyn.reportFilePaths=\
"C:\\Users\\phatd\\source\\repos\\CinemaBookingSystem\\.sonarqube\\out\\0\\Issues.json"
002A7D58-A1B1-CBE3-8F7A-0F0027BEE5A6.sonar.cs.scanner.telemetry=\
"C:\\Users\\phatd\\source\\repos\\CinemaBookingSystem\\.sonarqube\\out\\0\\Telemetry.json"

002A7D58-A1B1-CBE3-8F7A-0F0027BEE5A6.sonar.working.directory=C:\\Users\\phatd\\source\\repos\\CinemaBookingSystem\\.sonarqube\\out\\.sonar\\mod0
69D4494C-7D44-AE4E-8C0B-6DF71A7A42E4.sonar.projectKey=CinemaMicroservices:69D4494C-7D44-AE4E-8C0B-6DF71A7A42E4
69D4494C-7D44-AE4E-8C0B-6DF71A7A42E4.sonar.projectName=Cinema.Pricing.gRPC
69D4494C-7D44-AE4E-8C0B-6DF71A7A42E4.sonar.projectBaseDir=C:\\Users\\phatd\\source\\repos\\CinemaBookingSystem\\Cinema.Pricing.gRPC
69D4494C-7D44-AE4E-8C0B-6DF71A7A42E4.sonar.sourceEncoding=utf-8
69D4494C-7D44-AE4E-8C0B-6DF71A7A42E4.sonar.tests=
69D4494C-7D44-AE4E-8C0B-6DF71A7A42E4.sonar.sources=\
"C:\\Users\\phatd\\source\\repos\\CinemaBookingSystem\\Cinema.Pricing.gRPC\\appsettings.Development.json",\
"C:\\Users\\phatd\\source\\repos\\CinemaBookingSystem\\Cinema.Pricing.gRPC\\appsettings.json",\
"C:\\Users\\phatd\\source\\repos\\CinemaBookingSystem\\Cinema.Pricing.gRPC\\Dockerfile",\
"C:\\Users\\phatd\\source\\repos\\CinemaBookingSystem\\Cinema.Pricing.gRPC\\obj\\Cinema.Pricing.gRPC.csproj.nuget.dgspec.json",\
"C:\\Users\\phatd\\source\\repos\\CinemaBookingSystem\\Cinema.Pricing.gRPC\\obj\\project.assets.json",\
"C:\\Users\\phatd\\source\\repos\\CinemaBookingSystem\\Cinema.Pricing.gRPC\\Properties\\launchSettings.json",\
"C:\\Users\\phatd\\source\\repos\\CinemaBookingSystem\\Cinema.Pricing.gRPC\\bin\\Debug\\net8.0\\appsettings.Development.json",\
"C:\\Users\\phatd\\source\\repos\\CinemaBookingSystem\\Cinema.Pricing.gRPC\\bin\\Debug\\net8.0\\appsettings.json",\
"C:\\Users\\phatd\\source\\repos\\CinemaBookingSystem\\Cinema.Pricing.gRPC\\bin\\Debug\\net8.0\\Cinema.Pricing.gRPC.deps.json",\
"C:\\Users\\phatd\\source\\repos\\CinemaBookingSystem\\Cinema.Pricing.gRPC\\bin\\Debug\\net8.0\\Cinema.Pricing.gRPC.runtimeconfig.json",\
"C:\\Users\\phatd\\source\\repos\\CinemaBookingSystem\\Cinema.Pricing.gRPC\\bin\\Debug\\net8.0\\Cinema.Pricing.gRPC.staticwebassets.endpoints.json",\
"C:\\Users\\phatd\\source\\repos\\CinemaBookingSystem\\Cinema.Pricing.gRPC\\obj\\Debug\\net8.0\\rjsmcshtml.dswa.cache.json",\
"C:\\Users\\phatd\\source\\repos\\CinemaBookingSystem\\Cinema.Pricing.gRPC\\obj\\Debug\\net8.0\\rjsmrazor.dswa.cache.json",\
"C:\\Users\\phatd\\source\\repos\\CinemaBookingSystem\\Cinema.Pricing.gRPC\\obj\\Debug\\net8.0\\rpswa.dswa.cache.json",\
"C:\\Users\\phatd\\source\\repos\\CinemaBookingSystem\\Cinema.Pricing.gRPC\\obj\\Debug\\net8.0\\staticwebassets.build.endpoints.json",\
"C:\\Users\\phatd\\source\\repos\\CinemaBookingSystem\\Cinema.Pricing.gRPC\\obj\\Debug\\net8.0\\staticwebassets.build.json",\
"C:\\Users\\phatd\\source\\repos\\CinemaBookingSystem\\Cinema.Pricing.gRPC\\Program.cs",\
"C:\\Users\\phatd\\source\\repos\\CinemaBookingSystem\\Cinema.Pricing.gRPC\\Services\\PricingService.cs",\
"C:\\Users\\phatd\\source\\repos\\CinemaBookingSystem\\Cinema.Pricing.gRPC\\obj\\Debug\\net8.0\\Cinema.Pricing.gRPC.GlobalUsings.g.cs",\
"C:\\Users\\phatd\\source\\repos\\CinemaBookingSystem\\Cinema.Pricing.gRPC\\obj\\Debug\\net8.0\\.NETCoreApp,Version=v8.0.AssemblyAttributes.cs",\
"C:\\Users\\phatd\\source\\repos\\CinemaBookingSystem\\Cinema.Pricing.gRPC\\obj\\Debug\\net8.0\\Protos\\Pricing.cs",\
"C:\\Users\\phatd\\source\\repos\\CinemaBookingSystem\\Cinema.Pricing.gRPC\\obj\\Debug\\net8.0\\Protos\\PricingGrpc.cs",\
"C:\\Users\\phatd\\source\\repos\\CinemaBookingSystem\\Cinema.Pricing.gRPC\\obj\\Debug\\net8.0\\Cinema.Pricing.gRPC.AssemblyInfo.cs",\
"C:\\Users\\phatd\\source\\repos\\CinemaBookingSystem\\Cinema.Pricing.gRPC\\Protos\\pricing.proto"

69D4494C-7D44-AE4E-8C0B-6DF71A7A42E4.sonar.cs.analyzer.projectOutPaths=\
"C:\\Users\\phatd\\source\\repos\\CinemaBookingSystem\\.sonarqube\\out\\1"
69D4494C-7D44-AE4E-8C0B-6DF71A7A42E4.sonar.cs.roslyn.reportFilePaths=\
"C:\\Users\\phatd\\source\\repos\\CinemaBookingSystem\\.sonarqube\\out\\1\\Issues.json"
69D4494C-7D44-AE4E-8C0B-6DF71A7A42E4.sonar.cs.scanner.telemetry=\
"C:\\Users\\phatd\\source\\repos\\CinemaBookingSystem\\.sonarqube\\out\\1\\Telemetry.json"

69D4494C-7D44-AE4E-8C0B-6DF71A7A42E4.sonar.working.directory=C:\\Users\\phatd\\source\\repos\\CinemaBookingSystem\\.sonarqube\\out\\.sonar\\mod1
9E301E66-1B49-BE1B-F5E4-A6F25AE7F0E1.sonar.projectKey=CinemaMicroservices:9E301E66-1B49-BE1B-F5E4-A6F25AE7F0E1
9E301E66-1B49-BE1B-F5E4-A6F25AE7F0E1.sonar.projectName=Cinema.Booking.API
9E301E66-1B49-BE1B-F5E4-A6F25AE7F0E1.sonar.projectBaseDir=C:\\Users\\phatd\\source\\repos\\CinemaBookingSystem\\Cinema.Booking.API
9E301E66-1B49-BE1B-F5E4-A6F25AE7F0E1.sonar.sourceEncoding=utf-8
9E301E66-1B49-BE1B-F5E4-A6F25AE7F0E1.sonar.tests=
9E301E66-1B49-BE1B-F5E4-A6F25AE7F0E1.sonar.sources=\
"C:\\Users\\phatd\\source\\repos\\CinemaBookingSystem\\Cinema.Booking.API\\appsettings.Development.json",\
"C:\\Users\\phatd\\source\\repos\\CinemaBookingSystem\\Cinema.Booking.API\\appsettings.json",\
"C:\\Users\\phatd\\source\\repos\\CinemaBookingSystem\\Cinema.Booking.API\\Dockerfile",\
"C:\\Users\\phatd\\source\\repos\\CinemaBookingSystem\\Cinema.Booking.API\\obj\\Cinema.Booking.API.csproj.nuget.dgspec.json",\
"C:\\Users\\phatd\\source\\repos\\CinemaBookingSystem\\Cinema.Booking.API\\obj\\project.assets.json",\
"C:\\Users\\phatd\\source\\repos\\CinemaBookingSystem\\Cinema.Booking.API\\Properties\\launchSettings.json",\
"C:\\Users\\phatd\\source\\repos\\CinemaBookingSystem\\Cinema.Booking.API\\bin\\Debug\\net8.0\\appsettings.Development.json",\
"C:\\Users\\phatd\\source\\repos\\CinemaBookingSystem\\Cinema.Booking.API\\bin\\Debug\\net8.0\\appsettings.json",\
"C:\\Users\\phatd\\source\\repos\\CinemaBookingSystem\\Cinema.Booking.API\\bin\\Debug\\net8.0\\Cinema.Booking.API.deps.json",\
"C:\\Users\\phatd\\source\\repos\\CinemaBookingSystem\\Cinema.Booking.API\\bin\\Debug\\net8.0\\Cinema.Booking.API.runtimeconfig.json",\
"C:\\Users\\phatd\\source\\repos\\CinemaBookingSystem\\Cinema.Booking.API\\bin\\Debug\\net8.0\\Cinema.Booking.API.staticwebassets.endpoints.json",\
"C:\\Users\\phatd\\source\\repos\\CinemaBookingSystem\\Cinema.Booking.API\\obj\\Debug\\net8.0\\rjsmcshtml.dswa.cache.json",\
"C:\\Users\\phatd\\source\\repos\\CinemaBookingSystem\\Cinema.Booking.API\\obj\\Debug\\net8.0\\rjsmrazor.dswa.cache.json",\
"C:\\Users\\phatd\\source\\repos\\CinemaBookingSystem\\Cinema.Booking.API\\obj\\Debug\\net8.0\\rpswa.dswa.cache.json",\
"C:\\Users\\phatd\\source\\repos\\CinemaBookingSystem\\Cinema.Booking.API\\obj\\Debug\\net8.0\\staticwebassets.build.endpoints.json",\
"C:\\Users\\phatd\\source\\repos\\CinemaBookingSystem\\Cinema.Booking.API\\obj\\Debug\\net8.0\\staticwebassets.build.json",\
"C:\\Users\\phatd\\source\\repos\\CinemaBookingSystem\\Cinema.Booking.API\\Controllers\\BookingsController.cs",\
"C:\\Users\\phatd\\source\\repos\\CinemaBookingSystem\\Cinema.Booking.API\\Data\\AppDbContext.cs",\
"C:\\Users\\phatd\\source\\repos\\CinemaBookingSystem\\Cinema.Booking.API\\Models\\BookingTicket.cs",\
"C:\\Users\\phatd\\source\\repos\\CinemaBookingSystem\\Cinema.Booking.API\\Program.cs",\
"C:\\Users\\phatd\\source\\repos\\CinemaBookingSystem\\Cinema.Booking.API\\obj\\Debug\\net8.0\\Cinema.Booking.API.GlobalUsings.g.cs",\
"C:\\Users\\phatd\\source\\repos\\CinemaBookingSystem\\Cinema.Booking.API\\obj\\Debug\\net8.0\\.NETCoreApp,Version=v8.0.AssemblyAttributes.cs",\
"C:\\Users\\phatd\\source\\repos\\CinemaBookingSystem\\Cinema.Booking.API\\obj\\Debug\\net8.0\\Protos\\Pricing.cs",\
"C:\\Users\\phatd\\source\\repos\\CinemaBookingSystem\\Cinema.Booking.API\\obj\\Debug\\net8.0\\Protos\\PricingGrpc.cs",\
"C:\\Users\\phatd\\source\\repos\\CinemaBookingSystem\\Cinema.Booking.API\\obj\\Debug\\net8.0\\Cinema.Booking.API.AssemblyInfo.cs",\
"C:\\Users\\phatd\\source\\repos\\CinemaBookingSystem\\Cinema.Booking.API\\obj\\Debug\\net8.0\\Cinema.Booking.API.MvcApplicationPartsAssemblyInfo.cs",\
"C:\\Users\\phatd\\source\\repos\\CinemaBookingSystem\\Cinema.Booking.API\\Cinema.Booking.API.http",\
"C:\\Users\\phatd\\source\\repos\\CinemaBookingSystem\\Cinema.Booking.API\\Protos\\pricing.proto"

9E301E66-1B49-BE1B-F5E4-A6F25AE7F0E1.sonar.cs.analyzer.projectOutPaths=\
"C:\\Users\\phatd\\source\\repos\\CinemaBookingSystem\\.sonarqube\\out\\2"
9E301E66-1B49-BE1B-F5E4-A6F25AE7F0E1.sonar.cs.roslyn.reportFilePaths=\
"C:\\Users\\phatd\\source\\repos\\CinemaBookingSystem\\.sonarqube\\out\\2\\Issues.json"
9E301E66-1B49-BE1B-F5E4-A6F25AE7F0E1.sonar.cs.scanner.telemetry=\
"C:\\Users\\phatd\\source\\repos\\CinemaBookingSystem\\.sonarqube\\out\\2\\Telemetry.json"

9E301E66-1B49-BE1B-F5E4-A6F25AE7F0E1.sonar.working.directory=C:\\Users\\phatd\\source\\repos\\CinemaBookingSystem\\.sonarqube\\out\\.sonar\\mod2
sonar.host.url=http://localhost:9000
sonar.visualstudio.enable=false

sonar.modules=002A7D58-A1B1-CBE3-8F7A-0F0027BEE5A6,69D4494C-7D44-AE4E-8C0B-6DF71A7A42E4,9E301E66-1B49-BE1B-F5E4-A6F25AE7F0E1

